
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 13 22:48:25 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 9;
  public static final int AND = 7;
  public static final int DECIMAL = 14;
  public static final int FALSO = 16;
  public static final int SUMA = 2;
  public static final int UMENOS = 6;
  public static final int ENTERO = 13;
  public static final int MULTIPLICACION = 3;
  public static final int LLAVE_C = 12;
  public static final int EOF = 0;
  public static final int LLAVE_A = 11;
  public static final int IGUAL_QUE = 8;
  public static final int error = 1;
  public static final int DIVISION = 5;
  public static final int VERDADERO = 15;
  public static final int RESTA = 4;
  public static final int PAR_C = 10;
}

